//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО__Телеком_Нева_Связь_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmRequests
    {
        public int Id { get; set; }
        public string RequestNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int SubscriberId { get; set; }
        public string Service { get; set; }
        public string ServiceKindOf { get; set; }
        public string ServiceType { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string ProblemType { get; set; }
    
        public virtual Subscribers Subscribers { get; set; }
    }
}
