//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО__Телеком_Нева_Связь_.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Employees
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public string Type { get; set; }
        public string Number { get; set; }

        public string ImgPath
        {
            get
            {
                return "Resources/" + this.Number + ".jpg";
            }
        }
    }
}
